# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 556))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_offset = QtWidgets.QLabel(self.centralwidget)
        self.lbl_offset.setObjectName("lbl_offset")
        self.gridLayout.addWidget(self.lbl_offset, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mcu = QtWidgets.QWidget()
        self.tab_mcu.setObjectName("tab_mcu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_mcu)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PlotWidget = PlotWidget(self.tab_mcu)
        self.PlotWidget.setObjectName("PlotWidget")
        self.gridLayout_2.addWidget(self.PlotWidget, 0, 2, 20, 1)
        self.ch1_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch1_chkbox.setObjectName("ch1_chkbox")
        self.gridLayout_2.addWidget(self.ch1_chkbox, 0, 0, 1, 1)
        self.ch2_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch2_chkbox.setObjectName("ch2_chkbox")
        self.gridLayout_2.addWidget(self.ch2_chkbox, 1, 0, 1, 1)
        self.ch3_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch3_chkbox.setObjectName("ch3_chkbox")
        self.gridLayout_2.addWidget(self.ch3_chkbox, 2, 0, 1, 1)
        self.ch4_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch4_chkbox.setObjectName("ch4_chkbox")
        self.gridLayout_2.addWidget(self.ch4_chkbox, 3, 0, 1, 1)
        self.ch5_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch5_chkbox.setObjectName("ch5_chkbox")
        self.gridLayout_2.addWidget(self.ch5_chkbox, 4, 0, 1, 1)
        self.ch6_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch6_chkbox.setObjectName("ch6_chkbox")
        self.gridLayout_2.addWidget(self.ch6_chkbox, 5, 0, 1, 1)
        self.ch7_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch7_chkbox.setObjectName("ch7_chkbox")
        self.gridLayout_2.addWidget(self.ch7_chkbox, 6, 0, 1, 1)
        self.ch8_chkbox = QtWidgets.QCheckBox(self.tab_mcu)
        self.ch8_chkbox.setObjectName("ch8_chkbox")
        self.gridLayout_2.addWidget(self.ch8_chkbox, 7, 0, 1, 1)
        self.prescalar_label = QtWidgets.QLabel(self.tab_mcu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prescalar_label.sizePolicy().hasHeightForWidth())
        self.prescalar_label.setSizePolicy(sizePolicy)
        self.prescalar_label.setObjectName("prescalar_label")
        self.gridLayout_2.addWidget(self.prescalar_label, 8, 0, 1, 1)
        self.prescalar_spin = SpinBox(self.tab_mcu)
        self.prescalar_spin.setMaximumSize(QtCore.QSize(78, 22))
        self.prescalar_spin.setMinimum(1)
        self.prescalar_spin.setMaximum(200)
        self.prescalar_spin.setProperty("value", 1)
        self.prescalar_spin.setObjectName("prescalar_spin")
        self.gridLayout_2.addWidget(self.prescalar_spin, 9, 0, 1, 1)
        self.points_label = QtWidgets.QLabel(self.tab_mcu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points_label.sizePolicy().hasHeightForWidth())
        self.points_label.setSizePolicy(sizePolicy)
        self.points_label.setObjectName("points_label")
        self.gridLayout_2.addWidget(self.points_label, 10, 0, 1, 1)
        self.points_spin = SpinBox(self.tab_mcu)
        self.points_spin.setMaximumSize(QtCore.QSize(78, 22))
        self.points_spin.setMinimum(100)
        self.points_spin.setMaximum(1000)
        self.points_spin.setSingleStep(10)
        self.points_spin.setProperty("value", 200)
        self.points_spin.setObjectName("points_spin")
        self.gridLayout_2.addWidget(self.points_spin, 11, 0, 1, 1)
        self.mode_label = QtWidgets.QLabel(self.tab_mcu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_label.sizePolicy().hasHeightForWidth())
        self.mode_label.setSizePolicy(sizePolicy)
        self.mode_label.setObjectName("mode_label")
        self.gridLayout_2.addWidget(self.mode_label, 12, 0, 1, 1)
        self.trigger = QtWidgets.QComboBox(self.tab_mcu)
        self.trigger.setObjectName("trigger")
        self.trigger.addItem("")
        self.trigger.addItem("")
        self.gridLayout_2.addWidget(self.trigger, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_mcu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 14, 0, 1, 1)
        self.trigger_mode = QtWidgets.QComboBox(self.tab_mcu)
        self.trigger_mode.setObjectName("trigger_mode")
        self.trigger_mode.addItem("")
        self.trigger_mode.addItem("")
        self.trigger_mode.addItem("")
        self.gridLayout_2.addWidget(self.trigger_mode, 15, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 191, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 16, 0, 4, 1)
        self.tabWidget.addTab(self.tab_mcu, "")
        self.tab_pc = QtWidgets.QWidget()
        self.tab_pc.setObjectName("tab_pc")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_pc)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget.addTab(self.tab_pc, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 2, 14, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lbl_duty = QtWidgets.QLabel(self.centralwidget)
        self.lbl_duty.setObjectName("lbl_duty")
        self.gridLayout.addWidget(self.lbl_duty, 10, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.sld_duty = QtWidgets.QSlider(self.centralwidget)
        self.sld_duty.setMinimumSize(QtCore.QSize(0, 100))
        self.sld_duty.setMaximumSize(QtCore.QSize(16777215, 100))
        self.sld_duty.setMaximum(100)
        self.sld_duty.setOrientation(QtCore.Qt.Vertical)
        self.sld_duty.setObjectName("sld_duty")
        self.gridLayout.addWidget(self.sld_duty, 11, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.oblika_sel = QtWidgets.QComboBox(self.centralwidget)
        self.oblika_sel.setMinimumSize(QtCore.QSize(70, 0))
        self.oblika_sel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.oblika_sel.setObjectName("oblika_sel")
        self.oblika_sel.addItem("")
        self.oblika_sel.addItem("")
        self.oblika_sel.addItem("")
        self.oblika_sel.addItem("")
        self.gridLayout.addWidget(self.oblika_sel, 1, 0, 1, 1)
        self.lbl_amp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_amp.setObjectName("lbl_amp")
        self.gridLayout.addWidget(self.lbl_amp, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.frekvenca_spin = SpinBox(self.centralwidget)
        self.frekvenca_spin.setMinimumSize(QtCore.QSize(70, 0))
        self.frekvenca_spin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frekvenca_spin.setProperty("value", 1)
        self.frekvenca_spin.setObjectName("frekvenca_spin")
        self.gridLayout.addWidget(self.frekvenca_spin, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 12, 1, 1, 1)
        self.sld_offset = QtWidgets.QSlider(self.centralwidget)
        self.sld_offset.setMinimumSize(QtCore.QSize(0, 100))
        self.sld_offset.setMaximumSize(QtCore.QSize(16777215, 100))
        self.sld_offset.setMaximum(100)
        self.sld_offset.setOrientation(QtCore.Qt.Vertical)
        self.sld_offset.setObjectName("sld_offset")
        self.gridLayout.addWidget(self.sld_offset, 8, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.sld_amp = QtWidgets.QSlider(self.centralwidget)
        self.sld_amp.setMinimumSize(QtCore.QSize(0, 100))
        self.sld_amp.setMaximum(100)
        self.sld_amp.setOrientation(QtCore.Qt.Vertical)
        self.sld_amp.setObjectName("sld_amp")
        self.gridLayout.addWidget(self.sld_amp, 2, 1, 4, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.naklon_spin = SpinBox(self.centralwidget)
        self.naklon_spin.setMinimumSize(QtCore.QSize(70, 0))
        self.naklon_spin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.naklon_spin.setProperty("value", 1)
        self.naklon_spin.setObjectName("naklon_spin")
        self.gridLayout.addWidget(self.naklon_spin, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConnect_Disconnect = QtWidgets.QAction(MainWindow)
        self.actionConnect_Disconnect.setObjectName("actionConnect_Disconnect")
        self.actionCom_statistics = QtWidgets.QAction(MainWindow)
        self.actionCom_statistics.setObjectName("actionCom_statistics")
        self.menuFile.addAction(self.actionConnect_Disconnect)
        self.menuFile.addAction(self.actionCom_statistics)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.trigger.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DLOG_viewer"))
        self.lbl_offset.setText(_translate("MainWindow", "0.0"))
        self.ch1_chkbox.setText(_translate("MainWindow", "Ch1"))
        self.ch2_chkbox.setText(_translate("MainWindow", "Ch2"))
        self.ch3_chkbox.setText(_translate("MainWindow", "Ch3"))
        self.ch4_chkbox.setText(_translate("MainWindow", "Ch4"))
        self.ch5_chkbox.setText(_translate("MainWindow", "Ch5"))
        self.ch6_chkbox.setText(_translate("MainWindow", "Ch6"))
        self.ch7_chkbox.setText(_translate("MainWindow", "Ch7"))
        self.ch8_chkbox.setText(_translate("MainWindow", "Ch8"))
        self.prescalar_label.setText(_translate("MainWindow", "Prescalar"))
        self.points_label.setText(_translate("MainWindow", "Points"))
        self.mode_label.setText(_translate("MainWindow", "Trigger"))
        self.trigger.setItemText(0, _translate("MainWindow", "Ref_cnt"))
        self.trigger.setItemText(1, _translate("MainWindow", "Kot"))
        self.label_3.setText(_translate("MainWindow", "Mode"))
        self.trigger_mode.setItemText(0, _translate("MainWindow", "Normal"))
        self.trigger_mode.setItemText(1, _translate("MainWindow", "Single"))
        self.trigger_mode.setItemText(2, _translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mcu), _translate("MainWindow", "Grafi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pc), _translate("MainWindow", "Podatki"))
        self.label.setText(_translate("MainWindow", "Oblika"))
        self.lbl_duty.setText(_translate("MainWindow", "0.5"))
        self.label_9.setText(_translate("MainWindow", "Duty"))
        self.label_6.setText(_translate("MainWindow", "Amplituda"))
        self.oblika_sel.setItemText(0, _translate("MainWindow", "Konst"))
        self.oblika_sel.setItemText(1, _translate("MainWindow", "Step"))
        self.oblika_sel.setItemText(2, _translate("MainWindow", "Slew"))
        self.oblika_sel.setItemText(3, _translate("MainWindow", "Sine"))
        self.lbl_amp.setText(_translate("MainWindow", "0.0"))
        self.label_7.setText(_translate("MainWindow", "Frekvenca"))
        self.label_2.setText(_translate("MainWindow", "Offset"))
        self.label_5.setText(_translate("MainWindow", "Naklon"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionConnect_Disconnect.setText(_translate("MainWindow", "Connect/Disconnect"))
        self.actionCom_statistics.setText(_translate("MainWindow", "Com statistics"))

from pyqtgraph import PlotWidget, SpinBox
